select (count(distinct ?s) as ?count)
where {
  graph ?graph1 {
  ?s ?p1 ?o1 .
  }
  graph ?graph2 {
  ?s ?p2 ?o2 .
  }
  graph ?linksGraph {
    ?langS <http://www.w3.org/2002/07/owl#sameAs> ?s .
  }
  graph ?templateGraph1 {
    ?s <http://dbpedia.org/property/wikiPageUsesTemplate> ?t1 .
  }
  graph ?templateGraph2 {
   ?langS ?useTemplate2 ?t2 .
  }
  FILTER (?o1 != ?o2)
}