select ((count( distinct *)) as ?count)  where {

  graph ?graph1 {
    ?x ?prop ?y
  }
  MINUS {
  graph ?graph2 {
    ?x ?prop ?y
  }
        }
  FILTER(regex(str(?x), ?prefix , "i") && (str(?y) != "http://www.w3.org/2002/07/owl#Thing"))

}