select ((count( distinct ?class)) as ?count) where {

  graph ?graph1 {
    ?class a <http://www.w3.org/2000/01/rdf-schema#Class>
  }
  MINUS {
  graph ?graph2 {
    ?class a <http://www.w3.org/2000/01/rdf-schema#Class>
  }
        }
  FILTER(regex(str(?class), ?prefix , "i"))

}