prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>


select distinct ?s where  {
 graph <http://www.w3.org/ns/lemon/ontolex> {
    { ?s a owl:Class . }
    UNION
    { ?s a rdfs:Class . }
 }
}