prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


select distinct ?s where  {
 graph <http://www.w3.org/ns/lemon/ontolex> {
    { ?s a rdf:Property . }
    UNION
    { ?s a owl:DatatypeProperty . }
    UNION
    { ?s a owl:ObjectProperty }
    UNION
    { ?s a owl:OntologyProperty }
    UNION
    { ?s a owl:AnnotationProperty }
 }
}