select distinct ?tcount  where {
#?x ?p  ?s .
#?x <http://xmlns.com/foaf/0.1/primaryTopic> ?rdfdoc .

#?x <http://www.w3.org/2002/07/owl#sameAs>  ?y .
?s <http://rdfs.org/ns/void#triples> ?tcount;
   <http://rdfs.org/ns/void#property> ?p .
# OPTIONAL {
#   ?rdfdoc <http://www.w3.org/ns/dcat#downloadURL> ?url
#  }
}