select distinct ?url ?c where {

?void <http://rdfs.org/ns/void#propertyPartition> ?propPartition;
     <http://xmlns.com/foaf/0.1/primaryTopic> ?rdfdoc .

?propPartition <http://rdfs.org/ns/void#triples> ?c;
   <http://rdfs.org/ns/void#property> ?p .
 OPTIONAL {
   ?rdfdoc <http://www.w3.org/ns/dcat#downloadURL> ?url
  }
}